import { ProductItem } from "./types";

export const ALL_PRODUCTS: ProductItem[] = [
  // --- GUITARS (8 items) ---
  {
    id: "g-1",
    name: "Custom Stratocaster HSS '60s Vintage",
    category: "Guitars",
    subtitle: "Iconic tone. Hand-wound single coils with bridge humbucker punch.",
    price: 1799,
    originalPrice: 2199,
    rating: 4.9,
    reviewsCount: 382,
    soldCount: "1.4k+ sold",
    image: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Handcrafted with hand-wound custom single-coil pickups, alder body, and nitrocellulose lacquer finish for vintage resonance.",
    soundProfile: "Crisp bell-like highs, punchy mid-range dynamics, and legendary harmonic sustain.",
    variants: ["3-Tone Sunburst", "Olympic White", "Aged Seafoam Green"],
    specs: { "Body Wood": "Select Alder", "Neck": "Quartersawn Maple Modern 'C'", "Fretboard": "Rosewood, 9.5\" Radius", "Pickups": "Drum Palace Custom '60s Trio" }
  },
  {
    id: "g-2",
    name: "Acoustic Master Series Dreadnought Sitka",
    category: "Guitars",
    subtitle: "Solid Sitka spruce with mastergrade East Indian rosewood.",
    price: 2499,
    originalPrice: 2999,
    rating: 5.0,
    reviewsCount: 512,
    soldCount: "920+ sold",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=90",
    badge: "Top Brand",
    freeShipping: true,
    description: "Engineered with scalloped forward-shifted X-bracing to produce an expansive, balanced acoustic projection ideal for fingerstyle and powerful strumming.",
    soundProfile: "Deep resonant bass, articulate mids, and shimmering crystalline top-end.",
    variants: ["Natural Gloss", "Vintage Sunburst"],
    specs: { "Top": "Solid AAA Sitka Spruce", "Back & Sides": "Solid East Indian Rosewood", "Scale": "25.4 inches", "Nut & Saddle": "Bone" }
  },
  {
    id: "g-3",
    name: "Vintage Hollowbody Deluxe Semi-Acoustic",
    category: "Guitars",
    subtitle: "Warm acoustic chamber air meets vintage PAF humbucker warmth.",
    price: 2199,
    originalPrice: 2650,
    rating: 4.8,
    reviewsCount: 229,
    soldCount: "640+ sold",
    image: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "Semi-hollow chambered center-block design delivers creamy feedback resistance and rich jazz, blues, and alternative rock authority.",
    soundProfile: "Mellow, woody acoustic depth with singing sustain and vintage grit.",
    variants: ["Cherry Red", "Antique Ebony", "Heritage Gold"],
    specs: { "Body": "Laminated Flamed Maple", "Pickups": "Drum Palace Alnico II Dual Humbuckers", "Bridge": "Adjusto-Matic with Stopbar" }
  },
  {
    id: "g-4",
    name: "Artisan Grand Auditorium Cutaway Cedar",
    category: "Guitars",
    subtitle: "Western red cedar top with Tasmanian blackwood acoustic body.",
    price: 2299,
    originalPrice: 2799,
    rating: 4.9,
    reviewsCount: 175,
    soldCount: "430+ sold",
    image: "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Intimate fingerstyle acoustic response with Venetian cutaway and discreet onboard microphone pickup system.",
    soundProfile: "Warm, cedar harmonic bloom with sensitive dynamic touch.",
    variants: ["Natural Satin", "Tobacco Burst"],
    specs: { "Top": "Solid Western Red Cedar", "Back": "Tasmanian Blackwood", "Electronics": "Drum Palace PureAcoustic Dual System" }
  },
  {
    id: "g-5",
    name: "Modern Precision 5-String Bass Alder",
    category: "Guitars",
    subtitle: "Active/Passive preamp with high-mass bridge and thunderous low B.",
    price: 1899,
    originalPrice: 2250,
    rating: 4.9,
    reviewsCount: 310,
    soldCount: "810+ sold",
    image: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Built for stage foundation with graphite-reinforced maple neck and switchable 3-band active EQ.",
    soundProfile: "Tight, punchy low-end growl with piano-like harmonic clarity.",
    variants: ["Mystic Black", "Arctic White", "Sienna Burst"],
    specs: { "Strings": "5-String (Low B)", "Preamp": "18V Custom Active/Passive", "Neck": "Graphite-Reinforced Maple" }
  },
  {
    id: "g-6",
    name: "Classic Telecaster Custom Ash Body",
    category: "Guitars",
    subtitle: "Swamp ash body with brass barrel saddles and authentic twang.",
    price: 1699,
    originalPrice: 1999,
    rating: 4.8,
    reviewsCount: 420,
    soldCount: "1.2k+ sold",
    image: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "The classic rock and country standard with hand-beveled Alnico III bridge pickup and nitrocellulose neck.",
    soundProfile: "Biting bridge twang and warm, bell-tone neck response.",
    variants: ["Butterscotch Blonde", "2-Tone Sunburst"],
    specs: { "Body": "Lightweight Swamp Ash", "Bridge": "3-Saddle Vintage Brass", "Pickups": "Drum Palace '52 Vintage Custom" }
  },
  {
    id: "g-7",
    name: "Concert Classical Cedar Nylon 6-String",
    category: "Guitars",
    subtitle: "Traditional fan bracing with solid Canadian cedar and ebony fingerboard.",
    price: 1599,
    originalPrice: 1950,
    rating: 4.9,
    reviewsCount: 160,
    soldCount: "380+ sold",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Spanish-style concert acoustic with effortless nylon action and warm romantic projection.",
    soundProfile: "Lush, singing nylon trebles and deep Spanish bass timbre.",
    specs: { "Top": "Canadian Red Cedar", "Back": "Solid Rosewood", "Fretboard": "African Ebony" }
  },
  {
    id: "g-8",
    name: "Offset Jazzmaster Custom Soapbar P90",
    category: "Guitars",
    subtitle: "Floating tremolo with dual wide-bobbin single coils and rhythm circuit.",
    price: 1849,
    originalPrice: 2199,
    rating: 4.8,
    reviewsCount: 295,
    soldCount: "740+ sold",
    image: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Favored by indie and experimental artists, featuring smooth tremolo glide and rich surf harmonic resonance.",
    soundProfile: "Airy, chimey cleans with fat harmonic bloom under fuzz pedals.",
    variants: ["Sonic Blue", "Desert Sand", "Shell Pink"],
    specs: { "Tremolo": "Drum Palace Floating Glide", "Pickups": "Dual Soapbar '58 Jazz", "Scale": "25.5 inches" }
  },

  // --- KEYBOARDS (8 items) ---
  {
    id: "k-1",
    name: "Virtuoso Grand 88 Concert Stage Piano",
    category: "Keyboards",
    subtitle: "Graded real wood hammer keys & modeled acoustics.",
    price: 3899,
    originalPrice: 4500,
    rating: 4.9,
    reviewsCount: 194,
    soldCount: "310+ sold",
    image: "https://images.unsplash.com/photo-1552422535-c45813c61732?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "88-key genuine wooden keybeds paired with multi-dimensional acoustic resonance engine replicating European concert grand halls.",
    soundProfile: "Nuanced dynamic touch with sympathetic string and damper pedal resonance.",
    variants: ["Satin Black", "Polished White", "Dark Walnut"],
    specs: { "Keys": "88 Graded Real Wood Keybed", "Polyphony": "Infinite Modeled", "I/O": "USB-C MIDI, Balanced XLR Out" }
  },
  {
    id: "k-2",
    name: "Analog PolySynth 8 Voice Desktop Matrix",
    category: "Keyboards",
    subtitle: "8-Voice discrete analog polyphony with dual resonant filters.",
    price: 1999,
    originalPrice: 2399,
    rating: 4.9,
    reviewsCount: 460,
    soldCount: "1.1k+ sold",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "Pure analog signal path featuring 2 discrete VCOs per voice, resonant 4-pole low-pass filters, and hands-on matrix modulation.",
    soundProfile: "Massive analog pads, razor-sharp synth leads, and deep sub bass.",
    variants: ["Classic Aluminum", "Midnight Edition"],
    specs: { "Oscillators": "16 Discrete Analog VCOs", "Filters": "24dB/Oct Low-Pass", "Keybed": "61 Semi-Weighted Aftertouch" }
  },
  {
    id: "k-3",
    name: "Stage Studio Organ & Electromechanical Rhodes",
    category: "Keyboards",
    subtitle: "Physical LED drawbars with motorized tone wheel emulation.",
    price: 2299,
    originalPrice: 2700,
    rating: 4.8,
    reviewsCount: 168,
    soldCount: "420+ sold",
    image: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Vintage rotary speaker emulation with motorized drawbars and modeled vintage tines for authentic funk, soul, and gospel performance.",
    soundProfile: "Gritty tube rotary overdrive, mellow bell tines, and lush Leslie chorusing.",
    variants: ["Vintage Red", "Retro Walnut"],
    specs: { "Drawbars": "9 Physical LED-Indexed Drawbars", "Keys": "73 Waterfall Keybed", "Effects": "Tube Drive, Reverb" }
  },
  {
    id: "k-4",
    name: "Monophonic Bass Synthesizer Dual VCO",
    category: "Keyboards",
    subtitle: "Ladder filter circuitry with analog distortion drive.",
    price: 899,
    originalPrice: 1100,
    rating: 4.9,
    reviewsCount: 520,
    soldCount: "1.9k+ sold",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Delivers deep earth-shaking sub-bass, snappy acid sequences, and screaming analog lead sweeps.",
    soundProfile: "Fat saturated sub frequencies with gritty 24dB ladder filter self-oscillation.",
    specs: { "Circuits": "Discrete 100% Analog", "Keys": "25 Slim Velocity Keys", "Sequencer": "32-Step Arp Engine" }
  },
  {
    id: "k-5",
    name: "Wavetable Hybrid Synthesizer 16-Voice",
    category: "Keyboards",
    subtitle: "Stereo analog filters combined with deep wavetable warping.",
    price: 1749,
    originalPrice: 2099,
    rating: 4.9,
    reviewsCount: 230,
    soldCount: "680+ sold",
    image: "https://images.unsplash.com/photo-1552422535-c45813c61732?auto=format&fit=crop&w=1200&q=90",
    badge: "Top Brand",
    freeShipping: true,
    description: "Next-generation sonic soundscapes, cinematic evolutions, and shimmering crystal digital-analog hybrid timbres.",
    soundProfile: "Futuristic digital clarity grounded by warm discrete analog filters.",
    specs: { "Voices": "16 Stereo Voices", "Display": "OLED Interactive Graph", "Keys": "49 Full-Size Keys with Polyphonic Aftertouch" }
  },
  {
    id: "k-6",
    name: "Vintage 61-Key Combo Electric Organ",
    category: "Keyboards",
    subtitle: "Transistor circuitry with built-in multi-flange vibrato.",
    price: 1450,
    originalPrice: 1750,
    rating: 4.8,
    reviewsCount: 112,
    soldCount: "290+ sold",
    image: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "Recreates iconic psychedelic and 70s rock tone wheels with instantaneous tactile rocker tab switches.",
    soundProfile: "Piercing top-end organ bite and psychedelic vibrato warmth.",
    specs: { "Keys": "61 Waterfall", "Tabs": "14 Voicing Rocker Switches", "Outputs": "High-Z Tube Amp Out" }
  },
  {
    id: "k-7",
    name: "Drum Palace 88 Wooden MIDI Controller & Faders",
    category: "Keyboards",
    subtitle: "Precision hammer action studio master keyboard with motorized faders.",
    price: 1199,
    originalPrice: 1450,
    rating: 4.9,
    reviewsCount: 380,
    soldCount: "1.3k+ sold",
    image: "https://images.unsplash.com/photo-1552422535-c45813c61732?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "The ultimate centerpiece for DAW film scoring and virtual orchestral production.",
    soundProfile: "Flawless expressive velocity and polyphonic aftertouch response.",
    specs: { "Keybed": "88 Real Wooden Graded Hammer", "Controls": "9 Motorized 100mm Faders, 16 RGB Pads" }
  },
  {
    id: "k-8",
    name: "FM Digital Synth & Rhythm Groovebox",
    category: "Keyboards",
    subtitle: "6-Operator FM sound engine with 8-track polyphonic sequencer.",
    price: 799,
    originalPrice: 950,
    rating: 4.8,
    reviewsCount: 410,
    soldCount: "1.5k+ sold",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "Create intricate algorithmic rhythms, metallic bells, glassy basses, and punchy synth chords anywhere.",
    soundProfile: "Crisp 32-bit digital FM harmonics with analog overdrive distortion.",
    specs: { "Engine": "6-Operator 8-Voice FM", "Tracks": "8 Sequencer Tracks", "Power": "USB-C Bus Powered & Battery" }
  },

  // --- DRUMS & PERCUSSION (8 items) ---
  {
    id: "d-1",
    name: "Artisan Drum Craft Studio 5-Piece Shell Pack",
    category: "Drums",
    subtitle: "Hand-hammered bronze hardware with 7-ply Scandinavian birch.",
    price: 2699,
    originalPrice: 3200,
    rating: 4.9,
    reviewsCount: 185,
    soldCount: "530+ sold",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1200&q=90",
    badge: "Top Brand",
    freeShipping: true,
    description: "Crafted for recording clarity with 45-degree hand-sanded bearing edges and low-mass hardware for natural shell resonance.",
    soundProfile: "Tight controlled decay, punchy low-end punch, and articulate snare crack.",
    variants: ["Natural Birch Satin", "Deep Midnight Burst", "Vintage Marine Pearl"],
    specs: { "Shells": "7-Ply Scandinavian Birch", "Config": "22\" Kick, 10\"/12\" Toms, 16\" Floor, 14\" Snare", "Edges": "45° Hand-Cut" }
  },
  {
    id: "d-2",
    name: "Custom Phosphor Bronze Snare 14x6.5\"",
    category: "Drums",
    subtitle: "3mm seamless cast shell for explosive crack and sensitivity.",
    price: 849,
    originalPrice: 1050,
    rating: 5.0,
    reviewsCount: 341,
    soldCount: "1.8k+ sold",
    image: "https://images.unsplash.com/photo-1543443374-b6fe10a6ab7b?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Cast seamless bronze shell offering unmatched projection and wide dynamic sensitivity from delicate ghost notes to arena backbeats.",
    soundProfile: "Warm metallic body with explosive attack and focused overtone ring.",
    specs: { "Size": "14\" x 6.5\"", "Shell": "3mm Seamless Cast Bronze", "Wires": "20-Strand PureSound Custom" }
  },
  {
    id: "d-3",
    name: "Heritage Hand-Hammered Cymbal Master Set",
    category: "Drums",
    subtitle: "B20 Bronze cast cymbals: 14\" Hats, 16\" Crash, 18\" Crash, 21\" Ride.",
    price: 1299,
    originalPrice: 1599,
    rating: 4.9,
    reviewsCount: 260,
    soldCount: "890+ sold",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "Dark, complex, musical wash with shimmering stick definition, hand-lathed and hammered in traditional artisan style.",
    soundProfile: "Dark musical wash, buttery crash response, and pingy bell articulation.",
    specs: { "Alloy": "B20 Cast Bell Bronze", "Finish": "Raw Hand-Hammered & Traditional Lathed" }
  },
  {
    id: "d-4",
    name: "Club Jazz 4-Piece Maple Compact Shells",
    category: "Drums",
    subtitle: "18\" Bass drum with 100% North American hard rock maple.",
    price: 1999,
    originalPrice: 2400,
    rating: 4.8,
    reviewsCount: 140,
    soldCount: "350+ sold",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Ideal for club acoustics and acoustic jazz trios, delivering round melodic tom sustain and warm bop bass.",
    soundProfile: "Warm acoustic roundness and quick, musical dynamic decay.",
    variants: ["Vintage White Marine", "Walnut Satin"],
    specs: { "Kick": "18\" x 14\"", "Tom": "12\" x 8\"", "Floor Tom": "14\" x 14\"", "Wood": "North American Maple" }
  },
  {
    id: "d-5",
    name: "Drum Palace Pro Mesh Electronic Drum Flagship",
    category: "Drums",
    subtitle: "Multi-ply mesh heads with multi-zone positional sensing & studio module.",
    price: 2499,
    originalPrice: 2999,
    rating: 4.9,
    reviewsCount: 310,
    soldCount: "780+ sold",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Uncompromised acoustic feel with low room volume, multi-velocity round-robin sample library, and direct USB multi-track recording.",
    soundProfile: "Infinite studio kits with ultra-low latency response.",
    specs: { "Pads": "Full Wood Shells with 3-Ply Mesh", "Module": "Drum Palace Core DSP Multi-Track Out" }
  },
  {
    id: "d-6",
    name: "Solid Solid Maple Snare Drum 14x5.5\"",
    category: "Drums",
    subtitle: "Steam-bent single ply solid maple with reinforcement rings.",
    price: 799,
    originalPrice: 980,
    rating: 4.9,
    reviewsCount: 190,
    soldCount: "420+ sold",
    image: "https://images.unsplash.com/photo-1543443374-b6fe10a6ab7b?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Steam-bent from a single board of cured maple for pure tonal resonance and sensitive rimshots.",
    soundProfile: "Crisp woody punch with zero choke at high tension.",
    specs: { "Shell": "Solid Steam-Bent Maple", "Hoops": "Die-Cast Chrome" }
  },
  {
    id: "d-7",
    name: "Hand-Crafted African Mahogany Djembe 14\"",
    category: "Drums",
    subtitle: "Solid carved timber with premium select goatskin head.",
    price: 349,
    originalPrice: 450,
    rating: 5.0,
    reviewsCount: 420,
    soldCount: "1.6k+ sold",
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "Authentic deep bass tones and dry slaps, tuned with low-stretch alpine rope.",
    soundProfile: "Deep booming bass core with sharp, singing high slaps.",
    specs: { "Wood": "Sustainably Carved Mahogany", "Head": "Natural Unbleached Goatskin" }
  },
  {
    id: "d-8",
    name: "Pro Double Bass Drum Pedal CNC Aluminum",
    category: "Drums",
    subtitle: "Direct-drive zero-lag linkage with precision aircraft ball bearings.",
    price: 599,
    originalPrice: 750,
    rating: 4.9,
    reviewsCount: 280,
    soldCount: "950+ sold",
    image: "https://images.unsplash.com/photo-1543443374-b6fe10a6ab7b?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Built for lightning-fast double stroke control and effortless endurance.",
    soundProfile: "Ultra-linear pedal response with maximum footboard power.",
    specs: { "Drive": "Direct Drive Dual CNC Link", "Bearings": "Swiss High-Speed Bearing" }
  },

  // --- STUDIO & AUDIO (8 items) ---
  {
    id: "s-1",
    name: "Vintage Tube Studio Condenser Microphone",
    category: "Studio & Audio",
    subtitle: "Gold-sputtered dual capsule with 12AX7 vacuum valve tube.",
    price: 1499,
    originalPrice: 1850,
    rating: 4.9,
    reviewsCount: 620,
    soldCount: "2.1k+ sold",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Delivers the coveted 1960s vocal warmth, smooth high-frequency roll-off, and expansive 3D acoustic depth on vocals and strings.",
    soundProfile: "Silky, non-fatiguing high frequencies and intimate tube saturation.",
    specs: { "Capsule": "1-inch Gold-Sputtered Dual Diaphragm", "Tube": "Mullard 12AX7 Valve", "Patterns": "9 Switchable Polar Patterns" }
  },
  {
    id: "s-2",
    name: "Discrete 8-Channel Mic Preamp & Interface",
    category: "Studio & Audio",
    subtitle: "Class-A discrete transformer-coupled analog preamplification.",
    price: 1899,
    originalPrice: 2299,
    rating: 4.8,
    reviewsCount: 142,
    soldCount: "410+ sold",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "Custom Cinemag transformers provide +72dB of ultra-clean gain with rich analog color switches on every channel.",
    soundProfile: "Transparent, punchy transient response with selectable vintage iron transformer color.",
    specs: { "Gain": "Up to +72dB Clean Gain", "Transformers": "Discrete Input & Output Cinemag", "I/O": "8 XLR/TRS Inputs, USB-C" }
  },
  {
    id: "s-3",
    name: "Reference 8-Inch Active Studio Monitors (Pair)",
    category: "Studio & Audio",
    subtitle: "Beryllium dome tweeter with Kevlar woofer and DSP room tuning.",
    price: 1599,
    originalPrice: 1950,
    rating: 4.9,
    reviewsCount: 380,
    soldCount: "1.2k+ sold",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=90",
    badge: "Top Brand",
    freeShipping: true,
    description: "Pinpoint stereo imaging and surgical transient accuracy across 35Hz–40kHz for mixing and mastering.",
    soundProfile: "Flat, uncolored clinical frequency response with deep sub accuracy.",
    specs: { "Drivers": "8\" Custom Woven Kevlar + 1\" Pure Beryllium", "Power": "300W Bi-Amplified Class D" }
  },
  {
    id: "s-4",
    name: "Analog Master Stereo Bus Compressor 19\" Rack",
    category: "Studio & Audio",
    subtitle: "VCA glue compression with high-pass sidechain filter and dry/wet blend.",
    price: 2199,
    originalPrice: 2600,
    rating: 5.0,
    reviewsCount: 210,
    soldCount: "590+ sold",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "The classic British console master bus glue compressor with stepped mastering pots and harmonic drive.",
    soundProfile: "Tight mix glue, punchy drum dynamics, and transparent master cohesion.",
    specs: { "Topology": "Stereo Linked Quad VCA", "Chassis": "2U 19\" Rackmount Heavy Steel" }
  },
  {
    id: "s-5",
    name: "Open-Back Planar Magnetic Mixing Headphones",
    category: "Studio & Audio",
    subtitle: "Ultra-thin nanometer diaphragms with lambskin memory earcups.",
    price: 899,
    originalPrice: 1100,
    rating: 4.9,
    reviewsCount: 740,
    soldCount: "2.4k+ sold",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Experience room-like open soundstage with ultra-fast planar response and zero harmonic distortion.",
    soundProfile: "Expansive 3D spatial staging and immaculate micro-detail reproduction.",
    specs: { "Driver": "106mm Planar Magnetic", "Frequency": "5Hz - 50kHz", "Impedance": "32 Ohms" }
  },
  {
    id: "s-6",
    name: "Dynamic Studio Broadcast & Vocal Mic",
    category: "Studio & Audio",
    subtitle: "Internal pneumatic shock suspension with flat wide-range frequency.",
    price: 399,
    originalPrice: 499,
    rating: 4.9,
    reviewsCount: 1450,
    soldCount: "5.2k+ sold",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "The recording studio workhorse for loud guitar cabs, snare drums, and punchy broadcast vocals.",
    soundProfile: "Smooth warm midrange with excellent electromagnetic hum shielding.",
    specs: { "Type": "Dynamic Cardioid", "Shielding": "Internal Air Suspension & Pop Filter" }
  },
  {
    id: "s-7",
    name: "Custom Hand-Engraved Alto Saxophone",
    category: "Brass & Wind",
    subtitle: "Hand-engraved bell with resonant Japanese acoustic brass.",
    price: 2799,
    originalPrice: 3400,
    rating: 4.9,
    reviewsCount: 280,
    soldCount: "730+ sold",
    image: "https://images.unsplash.com/photo-1525994886773-080587e161c2?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Precision-drawn tone holes and Pisoni Italian leather pads deliver effortless low-register response and fluid jazz intonation.",
    soundProfile: "Lush, smoky sub-tones with singing upper harmonics and rapid key action.",
    variants: ["Vintage Gold Lacquer", "Brushed Matte Brass", "Silver Plated"],
    specs: { "Key": "Eb with High F#", "Pads": "Pisoni Pro Leather with Metal Resonators" }
  },
  {
    id: "s-8",
    name: "Artisan Solid Sterling Silver Concert Flute",
    category: "Brass & Wind",
    subtitle: ".925 Sterling silver headjoint, body, and French pointed arms.",
    price: 1999,
    originalPrice: 2450,
    rating: 4.9,
    reviewsCount: 190,
    soldCount: "510+ sold",
    image: "https://images.unsplash.com/photo-1573871669414-010dbf73ca84?auto=format&fit=crop&w=1200&q=90",
    badge: "Artisan",
    freeShipping: true,
    description: "Hand-cut embouchure hole crafted for immediate articulation, vibrant tonal colors, and flawless dynamic projection.",
    soundProfile: "Pure, shimmering high registers with a dark, resonant lower octave.",
    specs: { "Tubing": ".925 Sterling Silver Headjoint & Body", "Keys": "Open Hole, French Pointed" }
  },

  // --- ACCESSORIES (8 items) ---
  {
    id: "a-1",
    name: "Handcrafted Top-Grain Leather Instrument Strap",
    category: "Accessories",
    subtitle: "Supple Italian calfskin with memory foam padded suede backing.",
    price: 129,
    originalPrice: 179,
    rating: 5.0,
    reviewsCount: 1240,
    soldCount: "4.8k+ sold",
    image: "https://images.unsplash.com/photo-1550985543-f47f38aeee65?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Custom distressed oil-tanned leather designed for heavy instruments, ensuring zero shoulder fatigue during long studio and stage sessions.",
    variants: ["Whiskey Brown", "Dark Espresso", "Jet Black"],
    specs: { "Material": "Italian Full-Grain Leather", "Width": "3.25 Inches" }
  },
  {
    id: "a-2",
    name: "Solid American Walnut Studio Display Stand",
    category: "Accessories",
    subtitle: "Minimalist solid hardwood construction with nitro-safe plush.",
    price: 189,
    originalPrice: 240,
    rating: 4.9,
    reviewsCount: 890,
    soldCount: "3.2k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "Museum-grade hardwood display stand safe for nitrocellulose finishes and built to elevate any studio or living space.",
    specs: { "Wood": "Sustainably Harvested American Walnut", "Lining": "Nitro-Safe Plush Cushion" }
  },
  {
    id: "a-3",
    name: "Oxygen-Free Pure Copper Studio Cable 20ft",
    category: "Accessories",
    subtitle: "Gold-plated Neutrik jacks with braided tweed noise rejection jacket.",
    price: 69,
    originalPrice: 95,
    rating: 5.0,
    reviewsCount: 2100,
    soldCount: "8.4k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Preserves high frequency instrument sparkle with ultra-low capacitance shielding.",
    specs: { "Conductor": "99.99% OFC Pure Copper", "Connectors": "24K Gold Neutrik 1/4\"" }
  },
  {
    id: "a-4",
    name: "Precision Chromatic Strobe Stage Tuner Pedal",
    category: "Accessories",
    subtitle: "True bypass pedal with ±0.02 cents pitch detection accuracy.",
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviewsCount: 830,
    soldCount: "2.9k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Hot Deal",
    freeShipping: true,
    description: "Ultra-bright sunlight-visible strobe display with buffered or true bypass modes.",
    specs: { "Accuracy": "±0.02 Cents", "Housing": "Cast Aluminum Stompbox" }
  },
  {
    id: "a-5",
    name: "Flight-Ready Waterproof TSA Hardcase",
    category: "Accessories",
    subtitle: "Impact-resistant polypropylene shell with custom plush mold.",
    price: 329,
    originalPrice: 420,
    rating: 5.0,
    reviewsCount: 390,
    soldCount: "1.1k+ sold",
    image: "https://images.unsplash.com/photo-1550985543-f47f38aeee65?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Automated pressure equalization valve with TSA locking latches for world tours.",
    specs: { "Latches": "TSA Approved Trigger Release", "Rating": "IP67 Submersible Waterproof" }
  },
  {
    id: "a-6",
    name: "Artisan Solid Brass Capo with Micro-Tension",
    category: "Accessories",
    subtitle: "Uniform silicone pressure with zero fret buzz or retuning.",
    price: 59,
    originalPrice: 85,
    rating: 4.9,
    reviewsCount: 1620,
    soldCount: "6.1k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Engineered specifically to avoid pulling strings sharp when clamping.",
    specs: { "Material": "Solid Turned Brass", "Pad": "Dual-Density Silicone" }
  },
  {
    id: "a-7",
    name: "Pure Nickel Wound Precision Guitar Strings (3-Pack)",
    category: "Accessories",
    subtitle: "Warm vintage 1950s nickel formulation for smooth feel.",
    price: 38,
    originalPrice: 52,
    rating: 4.8,
    reviewsCount: 3100,
    soldCount: "12k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Bestseller",
    freeShipping: true,
    description: "Warm, full-bodied resonance with exceptional tuning stability.",
    specs: { "Gauges": "10-46 Regular Light", "Core": "Swedish High-Carbon Hex Steel" }
  },
  {
    id: "a-8",
    name: "Multi-Instrument Studio Power Supply Isolated 12-Port",
    category: "Accessories",
    subtitle: "Zero ground hum isolated toroid transformer for pedalboards.",
    price: 219,
    originalPrice: 280,
    rating: 5.0,
    reviewsCount: 470,
    soldCount: "1.7k+ sold",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=90",
    badge: "Choice",
    freeShipping: true,
    description: "Powers high-current digital pedals and vintage fuzz circuits silently.",
    specs: { "Outputs": "12 Fully Isolated Outputs (9V/12V/18V)", "Noise Floor": "<-140dBV" }
  }
];

export const CATEGORIES = [
  "Store",
  "Guitars",
  "Keyboards",
  "Drums",
  "Studio & Audio",
  "Brass & Wind",
  "Accessories"
];
